
let tmpl = '<div class="container table-container"><div class="table-thead row">'
  +'<div class="col-xs-3">'
    +'<div class="table-th">Category / Node / Property</div>'
  +'</div>'
  +'<div class="col-xs-9">'
    +'<div class="row table-thead">'
      +'<div class="table-th col-xs-6">Matched GDC Values</div>'
      +'<div class="table-th col-xs-6">CDE Permissible Values</div>'
    +'</div>'
  +'</div>'
+'</div>'
+'<div id="table-body" class="row table-body" style="max-height: {{:mh}}px;"><div class="col-xs-12">{{for values}}'
+'<div class="table-row row row-flex">'
  +'<div class="property table-td col-xs-3">'
      +'{{:category}}<ul><li class="word-break">{{:node}}<ul><li class="word-break">{{:name}}</li></ul></li></ul>'
      +'<a href="javascript:void(0)" class="gdc-details"><i class="fa fa-angle-down"></i> detail</a>'
      +'<div id="gdc-links" style="display: none;">'
        +'{{if local}}'
          +'<a href="javascript:getGDCData(\'{{:ref}}\',null);">See All Values</a></br>'
          +'<a href="javascript:toCompare(\'{{:ref}}\');"> Compare with User List</a></br>'
        +'{{/if}}'
        +'{{if syn}}'
          +'<a href="javascript:getGDCSynonyms(\'{{:ref}}\', \'{{:tgts_enum_n}}\');">See All Synonyms</a></br>'
        +'{{/if}}'
        +'{{if cdeId == ""}}'
          +''
        +'{{else}}'
          +'caDSR: <a class="table-td-link" href="{{:cdeUrl}}" target="_blank">CDE</a>'
          +'{{if local && cdeLen}}'
            +' , <a class="table-td-link" href="javascript:getCDEData(\'{{:cdeId}}\', \'{{:tgts_cde_n}}\');">Values</a> , <a class="table-td-link" href="javascript:compareGDC(\'{{:ref}}\',\'{{:cdeId}}\');"> Compare with GDC</a>'
          +'{{else cdeLen}}'
            +' , <a class="table-td-link" href="javascript:getCDEData(\'{{:cdeId}}\', \'{{:tgts_cde_n}}\');">Values</a>'
          +'{{else}}'
            +''
          +'{{/if}}'
        +'{{/if}}'
      +'</div>'
  +'</div>'
  +'<div class="col-xs-9 border-l"> {{for vs}}'
    +'<div class="row {{if #getIndex() > 4}}row-toggle row-flex{{else}}row-flex{{/if}}">'
      +'<div class="table-td col-xs-6 border-r border-b">{{if n == "no match"}}no match{{else}}<a href="javascript:getGDCData(\'{{:ref}}\',\'{{:n}}\');">{{if i_c !== undefined }}({{:i_c}}) {{else}}{{/if}}{{:n}}</a>{{/if}}</div>'
      +'<div class="table-td col-xs-6 border-b">'
        +'{{if cde_s.length }}'
        +'<div class="row">'
          +'<div class="col-xs-10">{{:cde_pv}}</div>'
          +'<div class="col-xs-2"><a href="javascript:void(0);" class="cde-collapser"><i class="fa fa-plus"></i></a></div>'
        +'</div>'
        +'<div id="cde-content" class="table-td" style="display: none;">'
          +'<div class="row">'
            +'<div class="col-xs-12">PV Meaning: {{:cde_pvm}}</div>'
          +'</div>' 
          +'{{for cde_s}}'
          +'<div class="row">'
            +'<div class="col-xs-3">{{:c}}</div>'
            +'<div class="col-xs-9">{{for s}}{{:}}</br>{{/for}}</div>'
          +'</div>'
          +'{{/for}}'
        +'</div>'
        +'{{/if}}'
      +'</div>'
    +'</div> {{/for}}' 
      +'{{if vs.length > 5}}'
        +'<div class="row row-flex"><div class="table-td col-xs-12 border-r">'
         +'<a class="table-td-link show-more-less" href="javascript:void(0);"><i class="fa fa-angle-down"></i> Show More ({{:vs.length - 5}})</a>'
        +'</div></div>'
      +'{{/if}}'
  +'</div>'

+'</div> {{/for}} </div></div></div>';


export default tmpl;

