
let tmpl = '<div class="container table-container"><div class="table-thead row">'
  +'<div class="col-xs-3">'
    +'<div class="table-th">Category / Node / Property</div>'
  +'</div>'
  +'<div class="col-xs-9">'
    +'<div class="row table-thead">'
      +'<div class="table-th col-xs-6">Matched GDC Values <a class="tooltip-box" data-toggle="tooltip" data-placement="bottom" title="Text will be provided to inform users on how to interpret content of columns."><i class="fa fa-info-circle"></i></a></div>'
      +'<div class="table-th col-xs-6">CDE Permissible Values <a class="tooltip-box" data-toggle="tooltip" data-placement="bottom" title="Text will be provided to inform users on how to interpret content of columns."><i class="fa fa-info-circle"></i></a></div>'
    +'</div>'
  +'</div>'
+'</div>'
+'<div id="table-body" class="row table-body" style="max-height: {{:mh}}px;"><div class="col-xs-12">{{for values}}'
+'<div class="table-row row row-flex">'
  +'<div class="property table-td col-xs-3">'
      +'{{:category}}<ul><li class="word-break">{{:node}}<ul><li class="word-break">{{:name}}</li></ul></li></ul>'
      +'<a href="javascript:void(0)" class="gdc-details"><i class="fa fa-angle-down"></i> detail</a>'
      +'<div id="gdc-links" style="display: none;">'
        +'{{if local}}'
          +'<a href="javascript:getGDCData(\'{{:ref}}\',null);">See All Values</a></br>'
          +'<a href="javascript:toCompare(\'{{:ref}}\');"> Compare with User List</a></br>'
        +'{{/if}}'
        +'{{if syn}}'
          +'<a href="javascript:getGDCSynonyms(\'{{:ref}}\', \'{{:tgts_enum_n}}\');">See All Terms</a></br>'
        +'{{/if}}'
        +'{{if cdeId == ""}}'
          +''
        +'{{else}}'
          +'caDSR: <a class="table-td-link" href="{{:cdeUrl}}" target="_blank">CDE</a>'
          +'{{if local && cdeLen}}'
            +' , <a class="table-td-link" href="javascript:getCDEData(\'{{:cdeId}}\', \'{{:tgts_cde_n}}\');">Values</a> , <a class="table-td-link" href="javascript:compareGDC(\'{{:ref}}\',\'{{:cdeId}}\');"> Compare with GDC</a>'
          +'{{else cdeLen}}'
            +' , <a class="table-td-link" href="javascript:getCDEData(\'{{:cdeId}}\', \'{{:tgts_cde_n}}\');">Values</a>'
          +'{{else}}'
            +''
          +'{{/if}}'
        +'{{/if}}'
      +'</div>'
  +'</div>'
  +'<div class="col-xs-9 border-l"> {{for vs}}'
    +'<div class="row {{if #getIndex() > 4}}row-toggle row-flex{{else}}row-flex{{/if}}">'
      +'<div class="table-td col-xs-6 border-r border-b">'
      +'{{if n == "no match"}}no match{{else}}'
        +'<div class="row">'
          +'<div class="col-xs-10"><a href="javascript:getGDCData(\'{{:ref}}\',\'{{:n}}\');">{{if i_c !== undefined }}{{:i_c}} {{:n}} (ICD-O-3){{else}}{{:n}}{{/if}}</a></div>'
          +'<div class="col-xs-2">{{if s.length }}<a href="javascript:void(0);" class="collapser"><i class="fa fa-plus"></i></a>{{/if}}</div>'
        +'</div>'
        +'<div id="data-content" class="table-td" style="display: none;">'
          +'<div class="row">'
            +'<div class="col-xs-4">'
              +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:ncitDetails(\'{{:n_c}}\');">{{:n_c}}</a> (NCIt)'
              +'{{* } else { }} {{:c}} {{*: (/^[E]/g).test(data.n_c) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
            +'</div>'
            +'<div class="col-xs-8">{{for s}}{{:}}</br>{{/for}}</div>'
          +'</div>'
        +'</div>'
      +'{{/if}}'
      +'</div>'
      +'<div class="table-td col-xs-6 border-b">'
        +'{{if cde_s.length }}'
        +'<div class="row">'
          +'<div class="col-xs-9">{{:cde_pv}}</div>'
          +'<div class="col-xs-3 cde-links">'
            +'<a href="javascript:void(0);" class="collapser"><i class="fa fa-plus"></i></a>'
            +'{{if n == "no match"}}<a href="javascript:void(0);" class="cde-suggest" style="float: right;">Suggest Item</a>{{/if}}'
          +'</div>'
        +'</div>'
        +'<div id="data-content" class="table-td" style="display: none;">'
          +'<div class="row">'
            +'<div class="table-td col-xs-12">PV Meaning (caDSR): {{:cde_pvm}}</div>'
          +'</div>' 
          +'{{for cde_s}}'
          +'<div class="row">'
            +'<div class="col-xs-4">'
            +'{{* if((/^C[1-9]/g).test(data.c)) { }}<a class="table-td-link" href="javascript:ncitDetails(\'{{:c}}\');">{{:c}}</a> (NCIt)'
            +'{{* } else { }} {{:c}} {{*: (/^[E]/g).test(data.c) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
            +'</div>'
            +'<div class="col-xs-8">{{for s}}{{:}}</br>{{/for}}</div>'
          +'</div>'
          +'{{/for}}'
        +'</div>'
        +'{{/if}}'
      +'</div>'
    +'</div> {{/for}}' 
      +'{{if vs.length > 5}}'
        +'<div class="row row-flex"><div class="table-td col-xs-12 border-r">'
         +'<a class="table-td-link show-more-less" href="javascript:void(0);"><i class="fa fa-angle-down"></i> Show More ({{:vs.length - 5}})</a>'
        +'</div></div>'
      +'{{/if}}'
  +'</div>'

+'</div> {{/for}} </div></div></div>'

+'<div id="alert-suggest" class="alert alert-suggest alert-info alert-dismissible" role="alert" style="display: none;">'
  +'An email will be sucessfully sent to <strong>GDC</strong> and <strong>EVS</strong> team.'
+'</div>';


export default tmpl;

