let tmpl = {
  header: '<div class="dialog__header">'
    +'<div class="dialog__titlebar">'
      +'<span id="ui-id-4" class="ui-dialog-title">GDC Values</span>'
      +'<button type="button" id="close_gdc_data" class="ui-button ui-corner-all ui-widget ui-button-icon-only ui-dialog-titlebar-close" title="Close"></button>'
      +'<span class="ui-label">{{:items_length}}</span>'
      +'{{if target !== null}}'
        +'<div class="checkbox ui-checkbox">'
          +'<label class="checkbox__label checkbox__label--height">'
            +'<input id="show_all_gdc_data" class="checkbox__input" type="checkbox" value="">'
            +'<span class="checkbox__btn"><i class="checkbox__icon fa fa-check"></i></span> Show all GDC values'
          +'</label>'
        +'</div>'
      +'{{/if}}'
    +'</div>'
      +'{{if icdo !== false}}'
      +'<div class="table__container">'
        +'<div class="table__thead row">'
          +'<div class="table__th col-xs-4">GDC Term</div>'
          +'<div class="table__th col-xs-3">ICD-O-3 Code</div>'
          +'<div class="table__th col-xs-5">ICD-O-3 Term</div>'
        +'</div>'
      +'</div>'
      +'{{/if}}'
  +'</div>',
  body:'<div id="gdc_data">'
    +'{{if icdo}}'
      +'<div class="table__container">'
        +'<div id="gdc-data-list" class="table__body row gdc-data-list" tabindex="0">'
          +'<div class="col-xs-12">'
            +'{{if target !== null }}'
              +'{{for items}}'
                +'{{if n == ~root.target }}'
                  +'<div class="table__row row" id="gdc_data_match">'
                    +'<div class="table__td table__td--slim col-xs-4">{{:n}}</div>'
                    +'<div class="table__td table__td--slim col-xs-3">{{if i_c}}{{if n == i_c.c}}<b>{{:i_c.c}}</b>{{else}}{{:i_c.c}}{{/if}}{{/if}}</div>'
                    +'<div class="table__td table__td--slim col-xs-5">{{if i_c}}{{if i_c.n}}{{for i_c.n}}{{:}}</br>{{/for}}{{else}}<b>{{:n}}</b>{{/if}}{{/if}}</div>'
                  +'</div>'
                +'{{else}}'
                  +'<div class="table__row row" style="display: none;">'
                    +'<div class="table__td table__td--slim col-xs-4">{{:n}}</div>'
                    +'<div class="table__td table__td--slim col-xs-3">{{if i_c}}{{:i_c.c}}{{/if}}</div>'
                    +'<div class="table__td table__td--slim col-xs-5">{{if i_c}}{{if i_c.n}}{{for i_c.n}}{{:}}</br>{{/for}}{{else}}{{:n}}{{/if}}{{/if}}</div>'
                  +'</div>'
                +'{{/if}}'
              +'{{/for}}'
            +'{{else}}'
              +'{{for items}}'
                +'<div class="table__row row">'
                  +'<div class="table__td table__td--slim col-xs-4">{{:n}}</div>'
                  +'<div class="table__td table__td--slim col-xs-3">{{if i_c}}{{:i_c.c}}{{/if}}</div>'
                  +'<div class="table__td table__td--slim col-xs-5">{{if i_c}}{{if i_c.n}}{{for i_c.n}}{{:}}</br>{{/for}}{{else}}{{:n}}{{/if}}{{/if}}</div>'
                +'</div>'
              +'{{/for}}'
            +'{{/if}}'
          +'</div>'
        +'</div>'
      +'</div>'
    +'{{else}}'
      +'<div class=" table__container table__container--blank">'
        +'<div id="gdc-data-list" class="table__body row gdc-data-list" tabindex="0">'
          +'<div class="col-xs-12">'
            +'{{if target !== null }}'
              +'{{for items}}'
                +'{{if n == ~root.target }}'
                  +'<div class="row" id="gdc_data_match">'
                    +'<div class="table__td table__td--xslim col-xs-12">{{:n}}</div>'
                  +'</div>'
                +'{{else}}'
                  +'<div class="row" style="display: none;">'
                    +'<div class="table__td table__td--xslim col-xs-12">{{:n}}</div>'
                  +'</div>'
                +'{{/if}}'
              +'{{/for}}'
            +'{{else}}'
              +'{{for items}}'
                +'<div class="row">'
                  +'<div class="table__td table__td--xslim col-xs-12">{{:n}}</div>'
                +'</div>'
              +'{{/for}}'
            +'{{/if}}'
          +'</div>'
        +'</div>'
      +'</div>'
    +'{{/if}}'
  +'</div>'
};

export default tmpl;
