
let tmpl = {
  gdc_data: '<div id="gdc_data">'
          +'{{if target !== null }}'
          +'<div class="option-right"><input type="checkbox" id="show_all_gdc_data"> Show all GDC values</div>'
          +'{{else}}'
          +''
          +'{{/if}}'
          +'<div class="clearfix"></div>'
          +'{{if icdo}}'
            +'<div class="table-container">'
              +'<div class="table-thead row">'
                +'<div class="table-th col-xs-4">ICD-O-3 Code</div>'
                +'<div class="table-th col-xs-8">ICD-O-3 Term</div>'
              +'</div>'
              +'<div id="gdc-data-list" class="table-body row" style="max-height: 390px;">'
                +'<div class="col-xs-12">'
                  +'{{if target !== null }}'
                    +'{{for items}}'
                      +'{{if n == ~root.target }}'
                        +'<div class="table-row row" id="gdc_data_match">'
                          +'<div class="table-td td-slim col-xs-4">{{:i_c.c}}</div><div class="table-td td-slim col-xs-8"><b>{{:n}}</b></div>'
                        +'</div>'
                      +'{{else}}'
                        +'<div class="table-row row" style="display: none;">'
                          +'<div class="table-td td-slim col-xs-4">{{:i_c.c}}</div><div class="table-td td-slim col-xs-8">{{:n}}</div>'
                        +'</div>'
                      +'{{/if}}'
                    +'{{/for}}'
                  +'{{else}}'
                    +'{{for items}}'
                      +'<div class="table-row row">'
                        +'<div class="table-td td-slim col-xs-4">{{:i_c.c}}</div><div class="table-td td-slim col-xs-8">{{:n}}</div>'
                      +'</div>'
                    +'{{/for}}'
                  +'{{/if}}'
                +'</div>'
              +'</div>'
            +'</div>'
          +'{{else}}'
            +'<div class="table-container-blank">'
              +'<div id="gdc-data-list" class="table-body row" style="max-height: 390px;">'
                +'<div class="col-xs-12">'
                  +'{{if target !== null }}'
                    +'{{for items}}'
                      +'{{if n == ~root.target }}'
                        +'<div class="row" id="gdc_data_match">'
                          +'<div class="table-td td-xs-slim col-xs-8"><b>{{:n}}</b></div>'
                        +'</div>'
                      +'{{else}}'
                        +'<div class="row" style="display: none;">'
                          +'<div class="table-td td-xs-slim col-xs-8">{{:n}}</div>'
                        +'</div>'
                      +'{{/if}}'
                    +'{{/for}}'
                  +'{{else}}'
                    +'{{for items}}'
                      +'<div class="row">'
                        +'<div class="table-td td-xs-slim col-xs-8">{{:n}}</div>'
                      +'</div>'
                    +'{{/for}}'
                  +'{{/if}}'
                +'</div>'
              +'</div>'
            +'</div>'
          +'{{/if}}'
        +'</div>',
  gdc_synonyms: '<div id="gdc_syn_data">'
          +'<div class="option-left"><input type="checkbox" id="gdc-data-invariant"> Show Duplicates</div>'
          +'{{if targets !== null }}'
            +'<div class="option-right"><input type="checkbox" id="show_all_gdc_syn"> Show all GDC values</div>'
          +'{{else}}'
            +''
          +'{{/if}}'
          +'<div class="clearfix"></div>'
          +'<div id="gdc-syn-data-list" class="table-container">'
            +'<div class="table-thead row">'
              +'{{if icdo}}<div class="table-th col-xs-2">ICD-O-3 Code</div>{{/if}}'
              +'<div class="table-th col-xs-3">ICD-O-3 Term</div>'
              +'<div class="table-th col-xs-2">NCIt Code</div>'
              +'<div class="table-th col-xs-5">NCIt Terms</div>'
            +'</div>'
            +'<div class="table-body row" style="max-height: 390px;">'
              +'<div class="col-xs-12">'
                +'{{for items}}'
                  +'{{if e == true || ~root.targets == null}}'
                    +'<div class="table-row row">'
                      +'{{if ~root.icdo}}<div class="table-td col-xs-2">{{:i_c.c}}</div>{{/if}}'
                      +'<div class="table-td col-xs-3">{{:n}}</div>'
                      +'<div class="table-td col-xs-2">'
                      +'{{if n_c && n_c !== ""}}'
                        +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:ncitDetails(\'{{:n_c}}\');" target="_blank">{{:n_c}}</a> (NCIt)'
                        +'{{* } else { }} {{:n_c}} {{*: (/^[E]/g).test(data.n_c) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
                      +'{{/if}}'
                      +'</div>'
                      +'<div name="syn_area" class="table-td col-xs-5">{{for s_r}}{{>#data}}<br>{{/for}}</div>'
                      +'<div name="syn_invariant" class="table-td col-xs-5" style="display: none;">'
                      +'{{for s}}{{>#data}}<br>{{/for}}'
                      +'</div>'
                    +'</div>'
                  +'{{else}}'
                    +'<div class="table-row row" style="display: none;">'
                      +'{{if ~root.icdo}}<div class="table-td col-xs-2">{{:i_c.c}}</div>{{/if}}'
                      +'<div class="table-td col-xs-3">{{:n}}</div>'
                      +'<div class="table-td col-xs-2">'
                      +'{{if n_c && n_c !== ""}}'
                        +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:ncitDetails(\'{{:n_c}}\');" target="_blank">{{:n_c}}</a> (NCIt)'
                        +'{{* } else { }} {{:n_c}} {{*: (/^[E]/g).test(data.n_c) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
                      +'{{/if}}'
                      +'</div>'
                      +'<div name="syn_area" class="table-td col-xs-5">{{for s_r}}{{>#data}}<br>{{/for}}</div>'
                      +'<div name="syn_invariant" class="table-td col-xs-5" style="display: none;">'
                      +'{{for s}}{{>#data}}<br>{{/for}}'
                      +'</div>'

                    +'</div>'
                  +'{{/if}}'
                +'{{/for}}'
              +'</div>'
            +'</div>'
          +'</div>'
        +'</div>',
  toCompare: '<div id="compare_dialog">'
                    +'<div id="compare_form">'
                        +'<div id="cp_top">'
                            +'<label class="left_label">User Defined Values:</label>'
                            +'<label class="right_label">GDC Values:</label>'
                            +'<div id="cp_left">'
                            +'<textarea id="cp_input" rows="10" cols="20" placeholder="Input values line by line" autocomplete="off"></textarea></div>'
                            +'<div id="cp_middle"></div>'
                            +'<div id="cp_right">'
                            +'{{for items}}'
                            +'<div>{{:n}}</div>'
                            +'{{/for}}'
                            +'</div>'
                        +'</div>'
                        +'<div id="cp_massage">'
                        +'</div>'
                        +'<div id="cp_bottom">'
                            +'<button id="compare" class="btn btn-default btn-submit-large">Compare</button>'
                            +'<button id="cancelCompare" class="btn btn-default btn-submit-large">Cancel</button>'
                        +'</div>'
                    +'</div>'
                    +'<div id="compare_result"></div>'
                +'</div>',
  cde_data: '<div id="caDSR_data">'
              +'<div class="data-option">'
                +'<div class="option-left"><input type="checkbox" id="cde-data-invariant"> Show Duplicates</div>'
                +'{{if targets !== null }}'
                  +'<div class="option-right"><input type="checkbox" id="show_all_cde_syn"> Show all GDE values</div>'
                +'{{else}}'
                  +''
                +'{{/if}}'
              +'</div>'
              +'<div class="clearfix"></div>'
              +'<div id="cde-syn-data-list" class="table-container">'
                +'<div class="table-thead row">'
                  +'<div class="table-th col-xs-2">PV</div>'
                  +'<div class="table-th col-xs-2">PV Meaning</div>'
                  +'<div class="table-th col-xs-4">Description</div>'
                  +'<div class="table-th col-xs-4">NCIt Code and Synonyms</div>'
                +'</div>'
                +'<div class="table-body row" style="max-height: 390px;">'
                  +'<div class="col-xs-12">'
                  +'{{for items}}'
                    +'{{if e == true || ~root.targets == null}}'
                    +'<div class="table-row row">'
                      +'<div class="table-td col-xs-2">{{:pv}}</div>'
                      +'<div class="table-td col-xs-2">{{:pvm}}</div>'
                      +'<div class="table-td col-xs-4">{{:pvd}}</div>'
                      +'<div name="syn_area" class="table-td col-xs-4">'
                      +'{{for i_rows}}'
                        +'<div class="row">'
                          +'<div class="col-lg-3 col-xs-12">'
                            +'{{* if((/^C[1-9]/g).test(data.pvc)) { }}<a class="table-td-link" href="javascript:ncitDetails(\'{{:pvc}}\');" target="_blank">{{:pvc}}</a> (NCIt)'
                            +'{{* } else if (data.pvc !== undefined) { }} {{:pvc}} {{*: (/^[E]/g).test(data.pvc) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
                          +'</div>'
                          +'<div class="col-lg-9 col-xs-12">{{for s}}{{>#data}}<br>{{/for}}</div>'
                        +'</div>' 
                      +'{{/for}}'
                      +'</div>'
                      +'<div name="syn_invariant" class="table-td col-xs-4" style="display: none;">'
                      +'{{for rows}}'
                        +'<div class="row">'
                          +'<div class="col-lg-3 col-xs-12">'
                            +'{{* if((/^C[1-9]/g).test(data.pvc)) { }}<a class="table-td-link" href="javascript:ncitDetails(\'{{:pvc}}\');" target="_blank">{{:pvc}}</a> (NCIt)'
                            +'{{* } else if (data.pvc !== undefined) { }} {{:pvc}} {{*: (/^[E]/g).test(data.pvc) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
                          +'</div>'
                          +'<div class="col-lg-9 col-xs-12">{{for s}}{{>#data}}<br>{{/for}}</div>'
                        +'</div>' 
                      +'{{/for}}'
                      +'</div>'
                    +'</div>'
                    +'{{else}}'
                    +'<div class="table-row row" style="display: none;">'
                      +'<div class="table-td col-xs-2">{{:pv}}</div>'
                      +'<div class="table-td col-xs-2">{{:pvm}}</div>'
                      +'<div class="table-td col-xs-4">{{:pvd}}</div>'
                      +'<div name="syn_area" class="table-td col-xs-4">'
                      +'{{for i_rows}}'
                        +'<div class="row">'
                          +'<div class="col-lg-3 col-xs-12">'
                            +'{{* if((/^C[1-9]/g).test(data.pvc)) { }}<a class="table-td-link" href="javascript:ncitDetails(\'{{:pvc}}\');" target="_blank">{{:pvc}}</a> (NCIt)'
                            +'{{* } else { }} {{:pvc}} {{*: (/^[E]/g).test(data.pvc) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
                          +'</div>'
                          +'<div class="col-lg-9 col-xs-12">{{for s}}{{>#data}}<br>{{/for}}</div>'
                        +'</div>' 
                      +'{{/for}}'
                      +'</div>'
                      +'<div name="syn_invariant" class="table-td col-xs-4" style="display: none;">'
                      +'{{for rows}}'
                        +'<div class="row">'
                          +'<div class="col-lg-3 col-xs-12">'
                            +'{{* if((/^C[1-9]/g).test(data.pvc)) { }}<a class="table-td-link" href="javascript:ncitDetails(\'{{:pvc}}\');" target="_blank">{{:pvc}}</a> (NCIt)'
                            +'{{* } else { }} {{:pvc}} {{*: (/^[E]/g).test(data.pvc) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
                          +'</div>'
                          +'<div class="col-lg-9 col-xs-12">{{for s}}{{>#data}}<br>{{/for}}</div>'
                        +'</div>' 
                      +'{{/for}}'
                      +'</div>'
                    +'</div>'
                    +'{{/if}}'
                  +'{{/for}}'
                  +'</div>'
                +'</div>'
              +'</div>'
            +'</div>',
  ncit_details: '<div id="ncit_details">'
      +'<p><b>Preferred Name:</b> {{:item.name}}</p>'
      +'{{if item.definition !== undefined}}<p><b>Definition:</b> {{:item.definition}}</p>{{/if}}'
      +'<p><b>NCI Thesaurus Code:</b> <a href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:item.code}}" target="_blank"">{{:item.code}}</a></p>'
      +'{{if item.synonyms.length }}<p><b>Synonyms &amp; Abbreviations:</b></p><p>{{for item.synonyms}}{{:}}</br>{{/for}}</p>{{/if}}'
      +'<p><a href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:item.code }}" target="_blank"">more details</p>'
      +'</div>'
};

export default tmpl;