
let tmpl = {
  gdc_data: '<div id="gdc_data">'
          +'{{if target !== null }}'
          +'<div class="option-right"><input type="checkbox" id="show_all"> Show all GDC values</div>'
          +'{{else}}'
          +''
          +'{{/if}}'
          +'<div id="gdc-data-list" class="div-list">'
          +'{{if target !== null }}'
            +'{{for items}}'
            +'{{if n == ~root.target }}'
            +'<div><b>{{:#getIndex() + 1}}.</b> {{:n}}</div>'
            +'{{else}}'
            +'<div style="display: none;"><b>{{:#getIndex() + 1 }}.</b>{{:n}}</div>'
            +'{{/if}}'
            +'{{/for}}'
          +'{{else}}'
            +'{{for items}}'
            +'<div><b>{{:#getIndex() + 1}}.</b> {{:n}}</div>'
            +'{{/for}}'
          +'{{/if}}'
          +'</div>'
          +'</div>',
  gdc_synonyms: '<div id="gdc_syn_data">'
          +'{{if targets !== null }}'
            +'<div class="option-right"><input type="checkbox" id="show_all"> Show all GDC values</div><div class="clearfix"></div>'
          +'{{else}}'
            +''
          +'{{/if}}'
          +'<div id="gdc-syn-data-list" class="table-container">'
            +'<div class="table-thead row">'
              +'<div class="table-th col-xs-1"></div>'
              +'{{if icdo}}<div class="table-th col-xs-2">ICDO_3_1 CODE</div>{{/if}}'
              +'<div class="table-th col-xs-3">PV</div>'
              +'<div class="table-th col-xs-3">NCIt</div>'
              +'<div class="table-th col-xs-5">Synonyms</div>'
            +'</div>'
            +'<div class="table-body row" style="max-height: 450px;">'
              +'<div class="col-xs-12">'
                +'{{for items}}'
                  +'{{if e == true || ~root.targets == null}}'
                    +'<div class="table-row row">'
                      +'<div class="table-td col-xs-1"><b>{{:#getIndex() + 1}}.</b></div>'
                      +'{{if ~root.icdo}}<div class="table-td col-xs-2">{{:i_c.c}}</div>{{/if}}'
                      +'<div class="table-td col-xs-3">{{:n}}</div>'
                      +'<div class="table-td col-xs-3">{{:n_c}}</div>'
                      +'<div class="table-td col-xs-5">{{for s}}{{>#data}}<br>{{/for}}</div>'
                    +'</div>'
                  +'{{else}}'
                    +'<div class="table-row row" style="display: none;">'
                      +'<div class="table-td col-xs-1"><b>{{:#getIndex() + 1}}.</b></div>'
                      +'{{if ~root.icdo}}<div class="table-td col-xs-2">{{:i_c.c}}</div>{{/if}}'
                      +'<div class="table-td col-xs-3">{{:n}}</div>'
                      +'<div class="table-td col-xs-3">{{:n_c}}</div>'
                      +'<div class="table-td col-xs-5">{{for s}}{{>#data}}<br>{{/for}}</div>'
                    +'</div>'
                  +'{{/if}}'
                +'{{/for}}'
              +'</div>'
            +'</div>'
          +'</div>'
          // +'<div class="div-list">'
          // +'<table id="gdc-syn-data-list" class="table"><tbody><tr class="data-table-head"><td width="5%"></td>{{if icdo}}<td width="15%">ICDO_3_1 CODE</td><td width="25%">PV</td><td width="10%">NCIt</td><td width="45%">Synonyms</td>{{else}}<td width="25%">PV</td><td width="25%">NCIt</td><td width="45%">Synonyms</td>{{/if}}</tr>'
          //   +'{{for items}}'
          //   +'{{if e == true || ~root.targets == null}}'
          //     +'<tr class="data-table-row"><td><b>{{:#getIndex() + 1}}.</b></td>{{if ~root.icdo}}<td>{{:i_c.c}}</td>{{/if}}<td>{{:n}}</td><td>{{:n_c}}</td><td>'
          //     +'{{for s}}'
          //     +'{{>#data}}<br>'
          //     +'{{/for}}'
          //     +'</td></tr>'
          //   +'{{else}}'
          //     +'<tr class="data-table-row" style="display: none;"><td><b>{{:#getIndex() + 1}}.</b></td>{{if ~root.icdo}}<td>{{:i_c.c}}</td>{{/if}}<td>{{:n}}</td><td>{{:n_c}}</td><td>'
          //     +'{{for s}}'
          //     +'{{>#data}}<br>'
          //     +'{{/for}}'
          //     +'</td></tr>'
          //   +'{{/if}}'
          //   +'{{/for}}'
          // +'</tbody></table></div>'
          +'</div>',
  toCompare: '<div id="compare_dialog">'
                    +'<div id="compare_form">'
                        +'<div id="cp_top">'
                            +'<label class="left_label">User Defined Values:</label>'
                            +'<label class="right_label">GDC Values:</label>'
                            +'<div id="cp_left">'
                            +'<textarea id="cp_input" rows="10" cols="20" placeholder="Input values line by line" autocomplete="off"></textarea></div>'
                            +'<div id="cp_middle"></div>'
                            +'<div id="cp_right">'
                            +'{{for items}}'
                            +'<div><b>{{:#getIndex() + 1}}.</b>{{:n}}</div>'
                            +'{{/for}}'
                            +'</div>'
                        +'</div>'
                        +'<div id="cp_massage">'
                        +'</div>'
                        +'<div id="cp_bottom">'
                            +'<button id="compare" class="btn btn-default btn-submit-large">Compare</button>'
                            +'<button id="cancelCompare" class="btn btn-default btn-submit-large">Cancel</button>'
                        +'</div>'
                    +'</div>'
                    +'<div id="compare_result"></div>'
                +'</div>',
  cde_data: '<div id="caDSR_data">'
              +'<div class="data-option">'
                +'<div class="option-left"><input type="checkbox" id="data-invariant"> Show Duplicates</div>'
                +'{{if targets !== null }}'
                  +'<div class="option-right"><input type="checkbox" id="show_all"> Show all GDE values</div>'
                +'{{else}}'
                  +''
                +'{{/if}}'
              +'</div>'
              +'<div class="clearfix"></div>'
              +'<div id="gde-syn-data-list" class="table-container">'
                +'<div class="table-thead row">'
                  +'<div class="table-th col-xs-1"></div>'
                  +'<div class="table-th col-xs-2">PV</div>'
                  +'<div class="table-th col-xs-2">PV Meaning</div>'
                  +'<div class="table-th col-xs-4">Description</div>'
                  +'<div class="table-th col-xs-3">NCIt Code and Synonyms</div>'
                +'</div>'
                +'<div class="table-body row" style="max-height: 450px;">'
                  +'<div class="col-xs-12">'
                  +'{{for items}}'
                    +'{{if e == true || ~root.targets == null}}'
                    +'<div class="table-row row">'
                      +'<div class="table-td col-xs-1"><b>{{:#getIndex() + 1}}.</b></div>'
                      +'<div class="table-td col-xs-2">{{:pv}}</div>'
                      +'<div class="table-td col-xs-2">test</div>'
                      +'<div class="table-td col-xs-4">{{:pvd}}</div>'
                      +'<div name="syn_area" class="table-td col-xs-3">'
                      +'{{for i_rows}}'
                        +'<div class="row">'
                          +'<div class="col-xs-3"><a class="table-td-link" href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:pvc}}" target="_blank">{{:pvc}}</a></div>'
                          +'<div class="col-xs-9">{{for s}}{{>#data}}<br>{{/for}}</div>'
                        +'</div>' 
                      +'{{/for}}'
                      +'</div>'
                      +'<div name="syn_invariant" class="table-td col-xs-3" style="display: none;">'
                      +'{{for rows}}'
                        +'<div class="row">'
                          +'<div class="col-xs-3"><a class="table-td-link" href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:pvc}}" target="_blank">{{:pvc}}</a></div>'
                          +'<div class="col-xs-9">{{for s}}{{>#data}}<br>{{/for}}</div>'
                        +'</div>' 
                      +'{{/for}}'
                      +'</div>'
                    +'</div>'
                    +'{{else}}'
                    +'<div class="table-row row" style="display: none;">'
                      +'<div class="table-td col-xs-1"><b>{{:#getIndex() + 1}}.</b></div>'
                      +'<div class="table-td col-xs-2">{{:pv}}</div>'
                      +'<div class="table-td col-xs-2">test</div>'
                      +'<div class="table-td col-xs-4">{{:pvd}}</div>'
                      +'<div name="syn_area" class="table-td col-xs-3">'
                      +'{{for i_rows}}'
                        +'<div class="row">'
                          +'<div class="col-xs-3"><a class="table-td-link" href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:pvc}}" target="_blank">{{:pvc}}</a></div>'
                          +'<div class="col-xs-9">{{for s}}{{>#data}}<br>{{/for}}</div>'
                        +'</div>' 
                      +'{{/for}}'
                      +'</div>'
                      +'<div name="syn_invariant" class="table-td col-xs-3" style="display: none;">'
                      +'{{for rows}}'
                        +'<div class="row">'
                          +'<div class="col-xs-3"><a class="table-td-link" href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:pvc}}" target="_blank">{{:pvc}}</a></div>'
                          +'<div class="col-xs-9">{{for s}}{{>#data}}<br>{{/for}}</div>'
                        +'</div>' 
                      +'{{/for}}'
                      +'</div>'
                    +'</div>'
                    +'{{/if}}'
                  +'{{/for}}'
                  +'</div>'
                +'</div>'
              +'</div>'
            // +'<div id="data-list" class="div-list">'

            //   +'<table class="table"><tbody id="gde-syn-data-list"><tr class="data-table-head"><td width="5%"></td><td width="15%">PV</td><td width="40%">Description</td><td width="40%">NCIt Code and Synonyms</td></tr>'
            //   +'{{for items}}'

            //   +'{{if e == true || ~root.targets == null}}'

            //   +'<tr class="data-table-row"><td><b>{{:#getIndex() + 1}}.</b></td><td>{{:pv}}</td><td>{{:pvd}}</td>'
            //   +'<td name="syn_area"><table class="table"><tbody>'
            //     +'{{for i_rows}}'
            //     +'<tr class=""><td class="w20"><a class="table-td-link" href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:pvc}}" target="_blank">{{:pvc}}</a></td><td class="w80 td-split">'
            //     +'{{for s}}'
            //     +'{{>#data}}<br>'
            //     +'{{/for}}'
            //     +'</td></tr>'
            //     +'{{/for}}'
            //   +'</tbody></table></td>'
            //   +'<td name="syn_invariant" style="display:none;">'
            //   +'<table class="table"><tbody>'
            //     +'{{for rows}}'
            //     +'<tr class=""><td class="w20"><a class="table-td-link" href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:pvc}}" target="_blank">{{:pvc}}</a></td><td class="w80 td-split">'
            //     +'{{for s}}'
            //     +'{{>#data}}<br>'
            //     +'{{/for}}'
            //     +'</td></tr>'
            //     +'{{/for}}'
            //   +'</tbody></table>'
            //   +'</td></tr>'

            //   +'{{else}}'

            //   +'<tr class="data-table-row" style="display: none;"><td><b>{{:#getIndex() + 1}}.</b></td><td>{{:pv}} {{:e}}</td><td>{{:pvd}}</td>'
            //   +'<td name="syn_area"><table class="table"><tbody>'
            //     +'{{for i_rows}}'
            //     +'<tr class=""><td class="w20"><a class="table-td-link" href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:pvc}}" target="_blank">{{:pvc}}</a></td><td class="w80 td-split">'
            //     +'{{for s}}'
            //     +'{{>#data}}<br>'
            //     +'{{/for}}'
            //     +'</td></tr>'
            //     +'{{/for}}'
            //   +'</tbody></table></td>'
            //   +'<td name="syn_invariant" style="display:none;">'
            //   +'<table class="table"><tbody>'
            //     +'{{for rows}}'
            //     +'<tr class=""><td class="w20"><a class="table-td-link" href="https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&code={{:pvc}}" target="_blank">{{:pvc}}</a></td><td class="w80 td-split">'
            //     +'{{for s}}'
            //     +'{{>#data}}<br>'
            //     +'{{/for}}'
            //     +'</td></tr>'
            //     +'{{/for}}'
            //   +'</tbody></table>'
            //   +'</td></tr>'
              
            //   +'{{/if}}'


            //   +'{{/for}}'
            //   +'</tbody></table></div>'
            +'</div>'
};

export default tmpl;