let tmpl = {
  header: '<div class="dialog__header">'
    +'<div class="dialog__titlebar">'
      +'<span id="ui-id-4" class="ui-dialog-title">GDC Terms</span>'
      +'<button type="button" id="close_gdc_terms_data" class="ui-button ui-corner-all ui-widget ui-button-icon-only ui-dialog-titlebar-close" title="Close"></button>'
      +'<span class="ui-label">{{:items_length}}</span>'
      +'<div class="checkbox ui-checkbox">'
        +'<label class="checkbox__label checkbox__label--height">'
          +'<input id="gdc-data-invariant" class="checkbox__input" type="checkbox" value="">'
          +'<span class="checkbox__btn"><i class="checkbox__icon fa fa-check"></i></span> Show Duplicates'
        +'</label>'
        +'{{if targets !== null}}'
        +'<label class="checkbox__label checkbox__label--height">'
          +'<input id="show_all_gdc_syn" class="checkbox__input" type="checkbox" value="">'
          +'<span class="checkbox__btn"><i class="checkbox__icon fa fa-check"></i></span> Show all GDC values'
        +'</label>'
        +'{{/if}}'
      +'</div>'
    +'</div>'
    +'<div class="table__container">'
      +'<div class="table__thead row">'
        +'{{if icdo}}'
        +'<div class="table__th col-xs-2">GDC Term</div>'
        +'<div class="table__th col-xs-2">ICD-O-3 Code</div>'
        +'<div class="table__th col-xs-3">ICD-O-3 Term</div>'
        +'{{else}}'
        +'<div class="table__th col-xs-7">GDC Term</div>'
        +'{{/if}}'
        +'<div class="table__th col-xs-2">NCIt Code</div>'
        +'<div class="table__th col-xs-3">NCIt Terms</div>'
      +'</div>'
    +'</div>'
  +'</div>',
  body: '<div id="gdc_terms_data">'
    +'<div id="gdc-syn-data-list" class="table__container">'
      +'<div class="table__body row">'
        +'<div class="col-xs-12">'
          +'{{for items}}'
            +'{{if e === true || ~root.targets.length == 0}}'
              +'<div class="table__row row">'
                +'{{if ~root.icdo}}'
                  +'<div class="table__td col-xs-2">{{:n}}</div>'
                  +'<div class="table__td col-xs-2">{{if i_c}}{{:i_c.c}}{{/if}}</div>'
                  +'<div class="table__td col-xs-3">{{if i_c}}{{if i_c.n}}{{for i_c.n}}{{:}}</br>{{/for}}{{else}}{{:n}}{{/if}}{{/if}}</div>'
                +'{{else}}'
                  +'<div class="table__td col-xs-7">{{:n}}</div>'
                +'{{/if}}'
                +'<div class="col-xs-5">'
                  +'{{if i_c !== undefined}}'
                    +'{{for i_c.n_syn}}'
                      +'<div class="row">'
                        +'<div class="table__td col-xs-4">'
                          +'{{if n_c !== undefined && n_c !== ""}}'
                            +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:getNCITDetails(\'{{:n_c}}\');">{{:n_c}}</a> (NCIt){{* } }}'
                          +'{{/if}}'
                        +'</div>'
                        +'<div name="syn_area" class="table__td col-xs-8">'
                          +'{{for s_r}}{{:}}<br>{{/for}}'
                        +'</div>'
                        +'<div name="syn_invariant" class="table__td col-xs-8" style="display: none;">{{for s}}{{:}}<br>{{/for}}</div>'
                      +'</div>'
                    +'{{/for}}'
                  +'{{else}}'
                    +'<div class="row">'
                      +'<div class="table__td col-xs-4">'
                        +'{{if n_c !== undefined && n_c !== ""}}'
                          +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:getNCITDetails(\'{{:n_c}}\');">{{:n_c}}</a> (NCIt){{* } }}'
                        +'{{/if}}'
                      +'</div>'
                      +'<div name="syn_area" class="table__td col-xs-8">{{for s_r}}{{:}}<br>{{/for}}</div>'
                      +'<div name="syn_invariant" class="table__td col-xs-8" style="display: none;">{{for s}}{{:}}<br>{{/for}}</div>'
                    +'</div>'
                  +'{{/if}}'
                +'</div>'
              +'</div>'
            +'{{else}}'
              +'<div class="table__row row" style="display: none;">'
                +'{{if ~root.icdo}}'
                  +'<div class="table__td col-xs-2">{{:n}}</div>'
                  +'<div class="table__td col-xs-2">{{if i_c}}{{:i_c.c}}{{/if}}</div>'
                  +'<div class="table__td col-xs-3">{{if i_c}}{{if i_c.n}}{{for i_c.n}}{{:}}</br>{{/for}}{{else}}{{:n}}{{/if}}{{/if}}</div>'
                +'{{else}}'
                  +'<div class="table__td col-xs-7">{{:n}}</div>'
                +'{{/if}}'
                +'<div class="col-xs-5">'
                  +'{{if i_c !== undefined}}'
                    +'{{for i_c.n_syn}}'
                      +'<div class="row">'
                        +'<div class="table__td col-xs-4">'
                          +'{{if n_c !== undefined && n_c !== ""}}'
                            +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:getNCITDetails(\'{{:n_c}}\');">{{:n_c}}</a> (NCIt){{* } }}'
                          +'{{/if}}'
                        +'</div>'
                        +'<div name="syn_area" class="table__td col-xs-8">{{for s_r}}{{:}}<br>{{/for}}</div>'
                        +'<div name="syn_invariant" class="table__td col-xs-8" style="display: none;">{{for s}}{{:}}<br>{{/for}}</div>'
                      +'</div>'
                    +'{{/for}}'
                  +'{{else}}'
                    +'<div class="row">'
                      +'<div class="table__td col-xs-4">'
                        +'{{if n_c !== undefined && n_c !== ""}}'
                          +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:getNCITDetails(\'{{:n_c}}\');">{{:n_c}}</a> (NCIt){{* } }}'
                        +'{{/if}}'
                      +'</div>'
                      +'<div name="syn_area" class="table__td col-xs-8">{{for s_r}}{{:}}<br>{{/for}}</div>'
                      +'<div name="syn_invariant" class="table__td col-xs-8" style="display: none;">{{for s}}{{:}}<br>{{/for}}</div>'
                    +'</div>'
                  +'{{/if}}'
                +'</div>'
              +'</div>'
            +'{{/if}}'
          +'{{/for}}'
        +'</div>'
      +'</div>'
    +'</div>'
  +'</div>'
}

export default tmpl;
