let tmpl = {
  header: '<div class="dialog__header">'
    +'<div class="dialog__titlebar">'
      +'<span id="ui-id-4" class="ui-dialog-title">GDC Terms</span>'
      +'<button type="button" id="close_gdc_terms_data" class="ui-button ui-corner-all ui-widget ui-button-icon-only ui-dialog-titlebar-close" title="Close"></button>'
      +'<span class="ui-label">{{:items_length}}</span>'
      +'<div class="checkbox ui-checkbox">'
        +'<label class="checkbox__label checkbox__label--height">'
          +'<input id="gdc-data-invariant" class="checkbox__input" type="checkbox" value="">'
          +'<span class="checkbox__btn"><i class="checkbox__icon fa fa-check"></i></span> Show Duplicates'
        +'</label>'
        +'{{if targets !== null}}'
        +'<label class="checkbox__label checkbox__label--height">'
          +'<input id="show_all_gdc_syn" class="checkbox__input" type="checkbox" value="">'
          +'<span class="checkbox__btn"><i class="checkbox__icon fa fa-check"></i></span> Show all GDC values'
        +'</label>'
        +'{{/if}}'
      +'</div>'
    +'</div>'
    +'<div class="table__container">'
      +'<div class="table__thead row">'
        +'{{if icdo}}'
        +'<div class="table__th col-xs-2">ICD-O-3 Code</div>'
        +'<div class="table__th col-xs-3">ICD-O-3 Term</div>'
        +'{{else}}'
        +'<div class="table__th col-xs-5">GDC Term</div>'
        +'{{/if}}'
        +'<div class="table__th col-xs-2">NCIt Code</div>'
        +'<div class="table__th col-xs-5">NCIt Terms</div>'
      +'</div>'
    +'</div>'
  +'</div>',
  body: '<div id="gdc_terms_data">'
    +'<div id="gdc-syn-data-list" class="table__container">'
      +'<div class="table__body row">'
        +'<div class="col-xs-12">'
          +'{{for items}}'
            +'{{if e == true || ~root.targets == null}}'
              +'<div class="table__row row">'
                +'{{if ~root.icdo}}'
                +'<div class="table__td col-xs-2">{{if i_c}}{{:i_c.c}}{{/if}}</div>'
                +'<div class="table__td col-xs-3">{{:n}}</div>'
                +'{{else}}'
                +'<div class="table__td col-xs-5">{{:n}}</div>'
                +'{{/if}}'
                +'<div class="table__td col-xs-2">'
                +'{{if n_c && n_c !== ""}}'
                  +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:getNCITDetails(\'{{:n_c}}\');">{{:n_c}}</a> (NCIt)'
                  +'{{* } else { }} {{:n_c}} {{*: (/^[E]/g).test(data.n_c) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
                +'{{/if}}'
                +'</div>'
                +'<div name="syn_area" class="table__td col-xs-5">{{for s_r}}{{>#data}}<br>{{/for}}</div>'
                +'<div name="syn_invariant" class="table__td col-xs-5" style="display: none;">'
                +'{{for s}}{{>#data}}<br>{{/for}}'
                +'</div>'
              +'</div>'
            +'{{else}}'
              +'<div class="table__row row" style="display: none;">'
                +'{{if ~root.icdo}}'
                +'<div class="table__td col-xs-2">{{if i_c}}{{:i_c.c}}{{/if}}</div>'
                +'<div class="table__td col-xs-3">{{:n}}</div>'
                +'{{else}}'
                +'<div class="table__td col-xs-5">{{:n}}</div>'
                +'{{/if}}'
                +'<div class="table__td col-xs-2">'
                +'{{if n_c && n_c !== ""}}'
                  +'{{* if((/^C[1-9]/g).test(data.n_c)) { }}<a class="table-td-link" href="javascript:getNCITDetails(\'{{:n_c}}\');">{{:n_c}}</a> (NCIt)'
                  +'{{* } else { }} {{:n_c}} {{*: (/^[E]/g).test(data.n_c) ? "(CTCAE)" : "(NCIt)" }} {{* } }}'
                +'{{/if}}'
                +'</div>'
                +'<div name="syn_area" class="table__td col-xs-5">{{for s_r}}{{>#data}}<br>{{/for}}</div>'
                +'<div name="syn_invariant" class="table__td col-xs-5" style="display: none;">'
                +'{{for s}}{{>#data}}<br>{{/for}}'
                +'</div>'

              +'</div>'
            +'{{/if}}'
          +'{{/for}}'
        +'</div>'
      +'</div>'
    +'</div>'
  +'</div>'
}

export default tmpl;
