
let tmpl = '<div class="container table__container"><div class="table__thead row table__thead--padding-right">'
  +'<div class="table__th col-xs-2">Category / Node</div>'
  +'<div class="table__th col-xs-2">Property</div>'
  +'<div class="table__th col-xs-4">Description</div>'
  +'<div class="table__th col-xs-2">GDC Property Values</div>'
  +'<div class="table__th col-xs-2">caDSR CDE Reference</div>'
+'</div>'
+'<div class="table__body table__body--overflow row" style="max-height: {{:options.height}}px;"><div class="col-xs-12">'
+'{{for props}}'
+'<div class="table__row row">'
  +'<div class="table__td col-xs-2">'
    +'<a href="{{if ~root.options.redirect}}https://docs.gdc.cancer.gov{{/if}}/Data_Dictionary/viewer/#?view=table-entity-list&anchor={{:ct}}" {{if ~root.options.redirect}}target="_blank"{{/if}}>{{:ct}}</a>'
    +'<ul><li class="table__td--word-break">'
      +'<a href="{{if ~root.options.redirect}}https://docs.gdc.cancer.gov{{/if}}/Data_Dictionary/viewer/#?view=table-definition-view&id={{:nd}}" {{if ~root.options.redirect}}target="_blank"{{/if}}>{{:nd}}</a>'
    +'</li></ul>'
  +'</div>'
  +'<div class="table__td col-xs-2 table__td--word-break">'
    +'<a href="{{if ~root.options.redirect}}https://docs.gdc.cancer.gov{{/if}}/Data_Dictionary/viewer/#?view=table-definition-view&id={{:nd}}&anchor={{:nm}}" {{if ~root.options.redirect}}target="_blank"{{/if}}>{{:nm}}</a>'
  +'</div>'
  +'<div class="table__td col-xs-4">{{:desc}}</div>'
  +'<div class="table__td col-xs-2">'
  +'{{if local}}'
  +'<a href="javascript:getGDCData(\'{{:ref}}\',null);">See All Values</a>'
  +'<br><a href="javascript:toCompare(\'{{:ref}}\');"> Compare with User List</a>'
    +'{{if syn}}'
    +'<br><a href="javascript:getGDCTerms(\'{{:ref}}\',null);">See All Terms</a>'
    +'{{else}}'
    +'{{/if}}'
  +'{{else}}'
  +'type: {{:type}}'
  +'{{/if}}'
  +'</div>'
  +'<div class="table__td col-xs-2">'
  +'{{if cdeId == ""}}'
  +''
  +'{{else}}'
  +'<a class="table-td-link" href="{{:cdeUrl}}" target="_blank">CDE</a>'
    +'{{if local && cdeLen}}'
    +', <a class="table-td-link" href="javascript:getCDEData(\'{{:cdeId}}\',null);">Values</a>, <a class="table-td-link" href="javascript:compareGDC(\'{{:ref}}\',\'{{:cdeId}}\');"> Compare with GDC</a>'
    +'{{else cdeLen}}'
    +', <a class="table-td-link" href="javascript:getCDEData(\'{{:cdeId}}\',null);">Values</a>'
    +'{{else}}'
    +''
    +'{{/if}}'
  +'{{/if}}'
  +'</div>'
+'</div>'
+'{{/for}}</div></div></div>';

export default tmpl;
