
let tmpl = '<div class="container table-container"><div class="table-thead row">'
  +'<div class="table-th col-xs-2">Category / Node</div>'
  +'<div class="table-th col-xs-2">Property</div>'
  +'<div class="table-th col-xs-4">Description</div>'
  +'<div class="table-th col-xs-2">GDC Property Values</div>'
  +'<div class="table-th col-xs-2">CDE Reference</div>'
+'</div>'
+'<div class="row table-body" style="max-height: {{:mh}}px;"><div class="col-xs-12">'
+'{{for props}}'
+'<div class="table-row row">'
  +'<div class="table-td col-xs-2">{{:ct}}<ul><li class="word-break">{{:nd}}</li></ul></div>'
  +'<div class="table-td col-xs-2 word-break">{{:nm}}</div>'
  +'<div class="table-td col-xs-4">{{:desc}}</div>'
  +'<div class="table-td col-xs-2">'
  +'{{if local}}'
  +'<a href="javascript:getGDCData(\'{{:ref}}\',null);">See All Values</a>'
  +'<br><a href="javascript:toCompare(\'{{:ref}}\');"> Compare with User List</a>'
    +'{{if syn}}'
    +'<br><a href="javascript:getGDCSynonyms(\'{{:ref}}\',null);">See All Terms</a>'
    +'{{else}}'
    +'{{/if}}'
  +'{{else}}'
  +'type: {{:type}}'
  +'{{/if}}'
  +'</div>' 
  +'<div class="table-td col-xs-2">'
  +'{{if cdeId == ""}}'
  +''
  +'{{else}}'
  +'caDSR: <a class="table-td-link" href="{{:cdeUrl}}" target="_blank">CDE</a>'
    +'{{if local && cdeLen}}'
    +' , <a class="table-td-link" href="javascript:getCDEData(\'{{:cdeId}}\',null);">Values</a> , <a class="table-td-link" href="javascript:compareGDC(\'{{:ref}}\',\'{{:cdeId}}\');"> Compare with GDC</a>'
    +'{{else cdeLen}}'
    +' , <a class="table-td-link" href="javascript:getCDEData(\'{{:cdeId}}\',null);">Values</a>'
    +'{{else}}'
    +''
    +'{{/if}}'
  +'{{/if}}'
  +'</div>'
+'</div>'
+'{{/for}}</div></div></div>';
  
export default tmpl;